### PR TITLE
Update bacon configuration package

### PR DESCRIPTION
**Pull request by yacuken**

### CODE REVIEW

**Review by sledges — COMMENTED** [review]
sorry for the delay 👻

**Comment by sledges** [comment]
I cleaned up by removing the merge commit, you can point this PR to my home, or if not possible, just clone the branch and adjust: https://github.com/sledges/droid-config-bacon/tree/from-yacuken

**Comment by yacuken** [comment]
rebased

**Comment by sledges** [comment]
Awesome thanks!

**Pull request merged**
